export default [
  {
    id: 1,
    res_id: 1,
    img: "foods/bbq-burger.jpg",
    name: "BBQ Burger",
    restaurent: "Cheap & Best Restaurent",
    cost: 78,
    delivery: 12,
    rating: 4,
    sold: 126,
    status: true,
  },
  {
    id: 1,
    res_id: 2,
    img: "foods/naga-burger.jpg",
    name: "Naga Burger",
    restaurent: "Amici Burger",
    cost: 65,
    delivery: 10,
    rating: 5,
    sold: 186,
    status: true,
  },
  {
    id: 1,
    res_id: 3,
    img: "foods/great-pizza.jpg",
    name: "Great Pizza",
    restaurent: "Haji Hotel",
    cost: 120,
    delivery: 15,
    rating: 5,
    sold: 225,
    status: false,
  },
  {
    id: 2,
    res_id: 1,
    img: "foods/pasta-noodles.jpg",
    name: "Pasta Noodles",
    restaurent: "Cheap & Best Restaurent",
    cost: 50,
    delivery: 11,
    rating: 4,
    sold: 52,
    status: true,
  },
];
