export default [
  {
    res_id: 1,
    res_name: "Cheap & Best Restaurent",
    img: "foods/bbq-burger.jpg",
    rating: 4,
    sold: 126,
    delivery_charge: 1,
  },
  {
    res_id: 2,
    res_name: "New Amici",
    img: "foods/naga-burger.jpg",
    rating: 5,
    sold: 58,
    delivery_charge: 1,
  },
  {
    res_id: 3,
    res_name: "Bismillah Hotel & Chiness Restaurent",
    img: "foods/great-pizza.jpg",
    rating: 4.5,
    sold: 85,
    delivery_charge: 1,
  },
  {
    res_id: 1,
    res_name: "Cheap & Best Restaurent",
    img: "foods/bbq-burger.jpg",
    rating: 4,
    sold: 126,
    delivery_charge: 1,
  },
  {
    res_id: 2,
    res_name: "New Amici",
    img: "foods/naga-burger.jpg",
    rating: 5,
    sold: 58,
    delivery_charge: 1,
  },
  {
    res_id: 3,
    res_name: "Bismillah Hotel & Chiness Restaurent",
    img: "foods/great-pizza.jpg",
    rating: 4.5,
    sold: 85,
    delivery_charge: 1,
  },
  {
    res_id: 1,
    res_name: "Cheap & Best Restaurent",
    img: "foods/bbq-burger.jpg",
    rating: 4,
    sold: 126,
    delivery_charge: 1,
  },
  {
    res_id: 2,
    res_name: "New Amici",
    img: "foods/naga-burger.jpg",
    rating: 5,
    sold: 58,
    delivery_charge: 1,
  },
  {
    res_id: 3,
    res_name: "Bismillah Hotel & Chiness Restaurent",
    img: "foods/great-pizza.jpg",
    rating: 4.5,
    sold: 85,
    delivery_charge: 1,
  },
  {
    res_id: 1,
    res_name: "Cheap & Best Restaurent",
    img: "foods/bbq-burger.jpg",
    rating: 4,
    sold: 126,
    delivery_charge: 1,
  },
  {
    res_id: 2,
    res_name: "New Amici",
    img: "foods/naga-burger.jpg",
    rating: 5,
    sold: 58,
    delivery_charge: 1,
  },
  {
    res_id: 3,
    res_name: "Bismillah Hotel & Chiness Restaurent",
    img: "foods/great-pizza.jpg",
    rating: 4.5,
    sold: 85,
    delivery_charge: 1,
  },
];
